# Generated by Django 3.2.8 on 2021-10-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_image_products_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
