# Generated by Django 3.2.8 on 2021-11-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='quantity',
            new_name='quan',
        ),
    ]
